name: Docker Image CI

on: [push]

permissions:
  contents: read
  packages: write
  id-token: write  # This is needed for OIDC federation.

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.0
      - 
        name: Chainguard Login
        uses: chainguard-dev/actions/setup-chainctl@main
        with:
          identity: 3e1bbf75871e9233b44648ebecdde5443b172469/19222debd54710aa
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/chainbear/jts3servermod
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}